### PR TITLE
Add warning about `createContainer` and `contextTypes`

### PR DESCRIPTION
**Pull request by jimmed**
This issue had my colleague bogged down for a good couple of hours - I hope this warning will help prevent others falling into the same trap!

### CODE REVIEW

**Comment by jhollingworth** [comment]
Hmm, interesting one. I'm wondering if theres a way that Marty can ensure that the app contextType is there before we render?

**Comment by taion** [comment]
You could make the context types property on the container class be read-only.

**Comment by jhollingworth** [comment]
@jimmed can you give me an example of how you were setting content types?

Was it 

```js
class User extends React.Component {}

User.contextTypes = { user: ... }
```
or

```js
var UserContainer = Marty.createContainer(User, {
  fetch: {
    user() { ... }
  }
})

UserContainer.contextTypes = { user: ... }
```

or something else?

**Comment by jimmed** [comment]
The latter of the two examples, so like this:

```
var UserContainer = Marty.createContainer(User, {
  fetch: {
    user() { ... }
  }
})

UserContainer.contextTypes = { user: ... }
```

The safe workaround was along these lines:

```
import assign from 'lodash/object/assign'; // or another Object.assign implementation...

const UserContainer = Marty.createContainer(User, { ... });

assign(UserContainer.contextTypes, { user: ... });
```

**Comment by jhollingworth** [comment]
You can pass in `contextTypes` into `createContainer` which will do the merge for you

```js
var UserContainer = Marty.createContainer(User, {
  contextTypes: { user: ... }
  fetch: {
    user() { ... }
  }
})
```

**Comment by jimmed** [comment]
Nice! Are you happy to update the docs yourself accordingly, or should I?

(making @moretti aware of this solution)

**Comment by moretti** [comment]
This is great, thanks!

**Comment by taion** [comment]
@jhollingworth 

What do you think about using `Object.defineProperty` to set `contextTypes` on the container so that this error condition isn't possible?

**Pull request closed without merging**
