### PR TITLE
Use underscore instead of tinydash

### PR DESCRIPTION
**Pull request by jhollingworth**

### CODE REVIEW

**Comment by jdalton** [comment]
Just a heads up [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) makes it easier to create smaller builds by cherry-picking the modules you want. For example see https://github.com/postaljs/postal.js/issues/91#issuecomment-73159144.

**Comment by jhollingworth** [comment]
Nice! I will have a look into this :)

I spent ages trying to pick various functions out of  lodash v2 but found certain functions would require in loads of other functions... I also quite liked the idea of [amp](http://amp.ampersandjs.com) but havent tired it out yet

**Comment by jdalton** [comment]
Amp [is considering](https://github.com/AmpersandJS/ampersand/pull/96#issuecomment-74551195) using lodash now too.

**Comment by jhollingworth** [comment]
Cool, well will investigate over the next few days. 

Out of interest can you require specific functions with lodash-for? I've been using it in a few places and loving it

**Comment by jdalton** [comment]
> Out of interest can you require specific functions with lodash-for? I've been using it in a few places and loving it

lodash-for? There's [individual npm packages](https://www.npmjs.com/browse/keyword/lodash-modularized) though I suspect you'll get smaller builds cherry-picking with `require('lodash/foo/bar')`.

**Comment by jhollingworth** [comment]
Damn autocorrect! I meant lodash-fp

Either way those individual NPM packages look perfect

**Comment by jdalton** [comment]
lodash-fp [will be getting](https://github.com/lodash/lodash-fp/issues/6#issuecomment-73997368) the ability to fp-ize cherry-picked methods, though still working on the name of it.

**Pull request merged**
